### ISSUE TITLE
wrong baseIRI

### ISSUE THREAD

**Issue by bourgeoa** [Otto-AA/solid-acl-parser#2]
The baseIRI used is /foo/file.acl and should be /foo/file
I think it could even be a blanknode but then as to be changed in all add rules
PR #1

**Comment by bourgeoa** [comment]
Seeing Travis test failed so you made it on purpose.
I tested the PR and it works perfectly.
The new rules are created with /foo/file that was the origin of my issue

**Comment by Otto-AA** [comment]
I don't really see, why it should be /foo/file. So I'd welcome it if you could explain it more.

As you can see in the tests, it currently creates the subject ids based on the acl file url. For instance "https://example.solid.community/.acl#owner" (instead of your proposed "https://example.solid.community/#owner"). I'd guess that this is ok, because usually something like `<#owner>` is used which maps to `<https://example.solid.community/.acl#owner>` afaik.

What I noticed is, that the AclDoc._defaultSubjectId is not really correct (it should be `aclUrl + #some-id` instead of `fileUrl + #some-id` or only `#some-id` if I see it correctly. I've created a PR which does the last version (see #2).

Could you take a look if this PR fixes your problem? If not, could you provide an example what you did to get the wrong result? Creating an acl doc and then parsing it to a turtle (If yes, what exactly)?
